#!/usr/bin/env ruby
require_relative 'game'

player_1 = Player.new("Player A")
player_2 = Player.new("Player B")
game = Game.new(player_1, player_2)

puts "Welcome to my special tic tac toe game!"
while game.is_not_over
  puts game.display_board
  puts "#{game.current_player.name}, please select your move number:"
  game.next_play(gets)
end
puts game.display_board + "Thank you for playing"
