#!/usr/bin/env ruby
require_relative 'game'

player_1 = Player.new("Player A", "X")
player_2 = Player.new("Player B", "O")
game = Game.new(player_1, player_2)

puts "Welcome to my special tic tac toe game!"
while game.over? != true
  puts game.board.display
  puts "#{game.current_player.name}, please select your move number:"
  game.next_play(gets)
end
puts game.board.display + "Thank you for playing"
