#!/usr/bin/env ruby
require_relative 'game'
require_relative 'player'

player_1 = Player.new("Player A", "X")
player_2 = Player.new("Player B", "O")
game = Game.new(player_1, player_2)

puts "Welcome to my special tic tac toe game!"
while game.over? != true
  puts game.board.display
  puts "#{game.current_player.name}, please select your move number:"
  position = gets
  game.next_play(position)
end
puts game.board.display + "Thank you for playing"
if game.board.winner
  name =  if game.board.winner == player_1.marker then player_1.name
          elsif game.board.winner == player_2.marker then player_.name
          end
  puts "Congratulations #{name}"
end
